# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'J.Todo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxSwift',    '~> 5'
    pod 'RxCocoa',    '~> 5'
  # Pods for J.Todo

  target 'J.TodoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'J.TodoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
